default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: rspec_rails_examples_database
  username: rspec_rails_examples_username
  password: rspec_rails_examples_password
  host: localhost
  port: 3306

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
